module.exports = {
    it: {
        translation: {
            POSITIVE_SOUND: `<audio src='soundbank://soundlibrary/ui/gameshow/amzn_ui_sfx_gameshow_positive_response_02'/>`,
            GREET_MSG: '$t(POSITIVE_SOUND) Ciao, questa skill ti permette di creare una nuova routine. ',
            CONTINUA: 'ok procediamo. Quando vuoi che venga attivata la routine {{nome}}? Di seguito sono riportate le 5 opzioni disponibili selezionane una oppure ripetila ad alta voce',
            GOODBYE_MSG: ['A presto! ', 'Ciao! ', 'Arrivederci! ', 'A dopo! '],
            LIST_OPZIONE_DETAIL_MSG: `hai selezionato {{person}}. Per confermare la tua scelta pronuncia procedi altrimenti seleziona un'altra opzione`,
            MSG_SVEGLIA_CANCELLATA: '`hai selezionato {{person}}. In questo modo la tua routine si attiverà quando cancellerai la sveglia, Per confermare la tua scelta pronuncia procedi altrimenti seleziona un\'altra opzione',
            MSG_VOCE: 'Bene',
            MSG_SUONI:'Bene hai scelto rilevamento suoni. La tua routine si attiverà quando rileverà un rumore specifico. Di seguito sono riportati i suoni disponibili, selezionane uno',
            MSG_VOCALE2:'che verrà attivata quando pronuncerai {{frase}}',
            PAUSA:'<break time="0.3s"/>',
            MSG_RILEVAMENTO:'hai scelto di impostare come suono da rilevare {{person.option.value}}. La routine quindi si attiverà quando Alexa rileverà questo suono',
            MSG_TEMPO: 'hai scelto {{person.option.value}}. Con questa azione Alexa ti fornirà le previsioni del tempo.',
            MSG_TEMPO1: 'hai scelto {{person}}. Con questa azione Alexa ti fornirà le previsioni del tempo.',
            MSG_APP:'hai scelto {{person.option.value}}. Con questa azione Alexa ti leggerà dalla tua agenda tutti gli appuntamenti del giorno.',
            MSG_APP1:'hai scelto {{person}}. Con questa azione Alexa ti leggerà dalla tua agenda tutti gli appuntamenti del giorno.',
            MSG_LUCI:'hai scelto {{person.option.value}}. Con questa azione Alexa gestirà le luci della tua casa, potrai dirle di accendere o spegnere una luce in una precisa stanza.',
            MSG_LUCI1:'hai scelto {{person}}. Con questa azione Alexa gestirà le luci della tua casa, potrai dirle di accendere o spegnere una luce in una precisa stanza.',
            MSG_MUSICA:'hai scelto {{person.option.value}}. Con questa azione Alexa riprodurrà musica dal tuo account.',
            MSG_MUSICA1:'hai scelto {{person}}. Con questa azione Alexa riprodurrà musica dal tuo account.',
            MSG_ALEXA:'hai scelto {{person.option.value}}. Se vuoi che Alexa ti canti una canzone oppure ti racconti una barzelletta o una storia devi dire canta una canzone, racconta una barzelletta, racconta una storia. oppure puoi semplicemente impostare una frase che alexa ti ripeterà.',
            MSG_ALEXA1:'hai scelto {{person}}. Se vuoi che Alexa ti canti una canzone oppure ti racconti una barzelletta o una storia devi dire canta una canzone, racconta una barzelletta, racconta una storia. oppure puoi semplicemente impostare una frase che alexa ti ripeterà.',
            MSG_TRAFFICO:'hai scelto {{person.option.value}}. Con questa azione Alexa ti informerà sulle condizioni del traffico.',
            MSG_TRAFFICO1:'hai scelto {{person}}. Con questa azione Alexa ti informerà sulle condizioni del traffico.',
            MSG_SVEGLIA:'hai scelto {{person.option.value}}. Con questa azione Alexa imposterà la sveglia ad un\'orario da te scelto.',
            MSG_SVEGLIA1:'hai scelto {{person}}. Con questa azione Alexa imposterà la sveglia ad un\'orario da te scelto.',
            MSG_TERMOSTATO:'hai scelto {{person.option.value}}. Con questa azione Alexa imposterà il termostato alla temperatura da te scelta.',
            MSG_TERMOSTATO1:'hai scelto {{person}}. Con questa azione Alexa imposterà il termostato alla temperatura da te scelta.',
            MSG_TAPPARELLE:'hai scelto {{person.option.value}}. Con questa azione Alexa gestirà le tapparelle della casa, potrai dirle di abbassare o alzare le tapparelle in una precisa stanza.',
            MSG_TAPPARELLE1:'hai scelto {{person}}. Con questa azione Alexa gestirà le tapparelle della casa, potrai dirle di abbassare o alzare le tapparelle in una precisa stanza.',
            MSG_TV: 'hai scelto {{person.option.value}}. Con questa azione Alexa gestirà la tua televisione, potrai dirle di accenderla o spegnerla.',
            MSG_TV1: 'hai scelto {{person}}. Con questa azione Alexa gestirà la tua televisione, potrai dirle di accenderla o spegnerla.',
            MSG_VOCALE:' che verrà attivata con il comando vocale {{frase}}.',
            MSG_PROGRAMMA:' che verrà attivata {{giorni}},',
            MSG_SUONIFINALE:'che verrà attivata quando rileverà {{suono}}',
            MSG_FINE:'$t(POSITIVE_SOUND) Bene, hai completato la tua routine {{nome}} ',
            MSG_ORE:'alle ore {{ora}}',
            MSG_ORARIO:'ok la routine verrà attivata {{giorni}}',
            REJECTED_MSG:'Nessun problema. Per favore ridimmi il nome e sistemiamo subito. ',
            REPROMPT_MSG: ` Se vuoi uscire basta che tu dica stop o esci`,
            AlexaLuci:' {{azione}} {{tipo}} {{stanza}} $t(PAUSA)',
            AlexaDice:' ti dirà {{frase}}. $t(PAUSA)',
            AlexaSveglia:' riprodurrà una sveglia alle ore {{oraSveglia}} $t(PAUSA)',
            TERMOSTATO:'imposterà il termostato a {{temperatura}} gradi $t(PAUSA)',
            MSG_TV2:'. Vuoi proseguire con l\'impostazione della televisione?',
            MSG_LUCI2:' .Vuoi proseguire con l\'impostazione delle luci?',
            MSG_ALEXA2:' .Vuoi proseguire con l\'impostazione di fai dire qualcosa?',
            MSG_SVEGLIA2:' .Vuoi proseguire con l\'impostazione della sveglia?',
            MSG_TAPPARELLE2:' .Vuoi proseguire con l\'impostazione per la gestione delle tapparelle?',
            MSG_TERMOSTATO2:' .Vuoi proseguire con l\'impostazione della temperatura del termostato?',
            MSG_MODIFICA:'. Ora se lo desideri puoi modificare la modalità d\'attivazione della routine oppure modificare o rimuovere le azioni, per farlo seleziona la voce desiderata. ',
            MSG_INIZIA_NUOVA_ROUTINE:'Se invece desideri creare un\'altra routine pronuncia crea una nuova routine',
            MSG_CONFERMA:'. Per confermare la tua scelta pronuncia aggiungi altrimenti seleziona un\'altra azione',
            MSG_CONFERMASUONO:' .Per confermare la tua scelta pronuncia imposta altrimenti seleziona un altro suono',
            AZIONI:' Di seguito sono presentate le 10 azioni che puoi aggiungere alla tua routine {{nome}}. Seleziona un\'azione per aggiungerla oppure ripetila ad alta voce. Quando hai finito per terminare pronuncia Salva routine',
            AGGIUNGI_AZIONE_O_SALVA: ' Pronuncia salva routine per salvare la routine oppure seleziona un\'altra azione.',
        }
    }
}